import { PrismaClient } from '@prisma/client'
import { PrismaPg } from '@prisma/adapter-pg'
import 'dotenv/config'

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
const prisma = new PrismaClient({ adapter })

const COMPANIONS = [
  {
    email: 'priya.sharma@demo.hana.app',
    name: 'Priya Sharma',
    displayName: 'Priya',
    age: 24,
    city: 'Mumbai',
    district: 'Bandra',
    bio: 'Bollywood enthusiast and foodie from Bandra. I know every hidden café, street food stall, and sunset spot in Mumbai. Let me show you the city through a local\'s eyes!',
    languages: ['Hindi', 'English', 'Marathi'],
    tags: ['food', 'cafés', 'Bollywood', 'photography'],
    hourlyRate: 1200,
    photos: [
      'https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Street Food Walk', emoji: '🍛' },
      { name: 'Café Hopping', emoji: '☕' },
      { name: 'Sunset at Marine Drive', emoji: '🌅' },
    ],
  },
  {
    email: 'ananya.iyer@demo.hana.app',
    name: 'Ananya Iyer',
    displayName: 'Ananya',
    age: 26,
    city: 'Bangalore',
    district: 'Koramangala',
    bio: 'Tech professional by day, art lover by evening. Bangalore\'s startup culture, craft beer scene, and live music venues are my playground. Let\'s explore together!',
    languages: ['Kannada', 'Tamil', 'English', 'Hindi'],
    tags: ['art', 'music', 'tech', 'craft beer'],
    hourlyRate: 1400,
    photos: [
      'https://images.unsplash.com/photo-1614644147798-f8c0fc9da7f6?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Art Gallery Tour', emoji: '🎨' },
      { name: 'Live Music Night', emoji: '🎵' },
      { name: 'Brewery Hop', emoji: '🍺' },
    ],
  },
  {
    email: 'kavya.nair@demo.hana.app',
    name: 'Kavya Nair',
    displayName: 'Kavya',
    age: 23,
    city: 'Kochi',
    district: 'Fort Kochi',
    bio: 'Born in God\'s Own Country. I\'ll take you through spice markets, backwater sunsets, and authentic Kerala cuisine. Every moment with me is a postcard.',
    languages: ['Malayalam', 'English', 'Hindi'],
    tags: ['culture', 'backwaters', 'spices', 'cuisine'],
    hourlyRate: 900,
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Spice Market Walk', emoji: '🌶️' },
      { name: 'Backwater Cruise', emoji: '🚣' },
      { name: 'Kerala Cuisine', emoji: '🍛' },
    ],
  },
  {
    email: 'meera.patel@demo.hana.app',
    name: 'Meera Patel',
    displayName: 'Meera',
    age: 27,
    city: 'Ahmedabad',
    district: 'Navrangpura',
    bio: 'Heritage walk guide and textile enthusiast. Ahmedabad\'s old city, pol houses, and vibrant fabric markets are my second home. UNESCO World Heritage, here we come!',
    languages: ['Gujarati', 'Hindi', 'English'],
    tags: ['heritage', 'textiles', 'history', 'architecture'],
    hourlyRate: 1000,
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Heritage Walk', emoji: '🏛️' },
      { name: 'Textile Market', emoji: '🧵' },
      { name: 'Pol House Tour', emoji: '🏘️' },
    ],
  },
  {
    email: 'riya.singh@demo.hana.app',
    name: 'Riya Singh',
    displayName: 'Riya',
    age: 25,
    city: 'Delhi',
    district: 'Hauz Khas',
    bio: 'Delhi girl with a passion for history and street art. From Mughal monuments to Hauz Khas Village\'s indie cafés — I know every corner of this chaotic, beautiful city.',
    languages: ['Hindi', 'Punjabi', 'English'],
    tags: ['history', 'street art', 'cafés', 'monuments'],
    hourlyRate: 1300,
    photos: [
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Monument Tour', emoji: '🕌' },
      { name: 'Street Art Walk', emoji: '🎭' },
      { name: 'Indie Café Crawl', emoji: '☕' },
    ],
  },
  {
    email: 'divya.krishnan@demo.hana.app',
    name: 'Divya Krishnan',
    displayName: 'Divya',
    age: 28,
    city: 'Chennai',
    district: 'Mylapore',
    bio: 'Classical Bharatanatyam dancer and Carnatic music lover. I\'ll introduce you to Chennai\'s rich cultural soul  temples, sabhas, filter coffee, and the Marina at dawn.',
    languages: ['Tamil', 'English', 'Telugu'],
    tags: ['classical dance', 'music', 'temples', 'culture'],
    hourlyRate: 1100,
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Temple Walk', emoji: '🛕' },
      { name: 'Carnatic Concert', emoji: '🎶' },
      { name: 'Filter Coffee Tour', emoji: '☕' },
    ],
  },
  {
    email: 'sneha.desai@demo.hana.app',
    name: 'Sneha Desai',
    displayName: 'Sneha',
    age: 22,
    city: 'Pune',
    district: 'Koregaon Park',
    bio: 'Fitness coach and wellness enthusiast. Pune\'s hills, parks, and yoga studios are my playground. Let\'s start your day with a sunrise hike or a mindful morning walk!',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['fitness', 'yoga', 'hiking', 'wellness'],
    hourlyRate: 950,
    photos: [
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Sunrise Hike', emoji: '🌄' },
      { name: 'Yoga Session', emoji: '🧘' },
      { name: 'Wellness Walk', emoji: '🌿' },
    ],
  },
  {
    email: 'aisha.khan@demo.hana.app',
    name: 'Aisha Khan',
    displayName: 'Aisha',
    age: 26,
    city: 'Hyderabad',
    district: 'Charminar',
    bio: 'Hyderabadi through and through. Biryani trails, pearl markets, Charminar evenings — I\'ll show you the Nizam\'s city in all its layered, fragrant glory.',
    languages: ['Urdu', 'Telugu', 'Hindi', 'English'],
    tags: ['biryani', 'pearls', 'history', 'food'],
    hourlyRate: 1050,
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Biryani Trail', emoji: '🍚' },
      { name: 'Pearl Market', emoji: '💎' },
      { name: 'Charminar Evening', emoji: '🕌' },
    ],
  },
  {
    email: 'pooja.verma@demo.hana.app',
    name: 'Pooja Verma',
    displayName: 'Pooja',
    age: 29,
    city: 'Jaipur',
    district: 'Pink City',
    bio: 'Rajasthani royalty vibes, zero pretension. Palaces, block printing workshops, chai with a view — Jaipur is magical and I\'m your guide to every pink-walled secret.',
    languages: ['Rajasthani', 'Hindi', 'English'],
    tags: ['palaces', 'block printing', 'chai', 'royalty'],
    hourlyRate: 1150,
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Palace Tour', emoji: '🏰' },
      { name: 'Block Print Workshop', emoji: '🖨️' },
      { name: 'Rooftop Chai', emoji: '🍵' },
    ],
  },
  {
    email: 'nisha.reddy@demo.hana.app',
    name: 'Nisha Reddy',
    displayName: 'Nisha',
    age: 24,
    city: 'Bangalore',
    district: 'Indiranagar',
    bio: 'Bookworm, coffee snob, and indie film lover. Bangalore\'s independent bookstores, specialty coffee roasters, and arthouse cinemas are my happy places.',
    languages: ['Telugu', 'Kannada', 'English', 'Hindi'],
    tags: ['books', 'coffee', 'indie films', 'art'],
    hourlyRate: 1250,
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Bookstore Crawl', emoji: '📚' },
      { name: 'Specialty Coffee', emoji: '☕' },
      { name: 'Arthouse Cinema', emoji: '🎬' },
    ],
  },
  {
    email: 'tara.menon@demo.hana.app',
    name: 'Tara Menon',
    displayName: 'Tara',
    age: 27,
    city: 'Mumbai',
    district: 'Colaba',
    bio: 'Marine biologist and ocean lover. From Colaba\'s colonial architecture to Versova\'s fishing village — I see Mumbai\'s layers that most visitors miss.',
    languages: ['Malayalam', 'Hindi', 'English'],
    tags: ['ocean', 'architecture', 'history', 'nature'],
    hourlyRate: 1350,
    photos: [
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Colonial Walk', emoji: '🏛️' },
      { name: 'Fishing Village', emoji: '🎣' },
      { name: 'Sunset Sail', emoji: '⛵' },
    ],
  },
  {
    email: 'simran.kaur@demo.hana.app',
    name: 'Simran Kaur',
    displayName: 'Simran',
    age: 25,
    city: 'Amritsar',
    district: 'Golden Temple Area',
    bio: 'Punjabi soul with a warm heart. The Golden Temple at dawn, langar, Wagah Border ceremony, and the best lassi in Punjab — I\'ll give you an experience that stays forever.',
    languages: ['Punjabi', 'Hindi', 'English'],
    tags: ['spirituality', 'food', 'culture', 'history'],
    hourlyRate: 850,
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Golden Temple Dawn', emoji: '✨' },
      { name: 'Wagah Border', emoji: '🇮🇳' },
      { name: 'Lassi & Kulcha', emoji: '🥛' },
    ],
  },
  {
    email: 'ishita.bose@demo.hana.app',
    name: 'Ishita Bose',
    displayName: 'Ishita',
    age: 28,
    city: 'Kolkata',
    district: 'Park Street',
    bio: 'Bengali intellectual with a love for adda, mishti doi, and Rabindra Sangeet. Kolkata\'s trams, bookstalls, and Durga Puja magic — let me be your guide to the City of Joy.',
    languages: ['Bengali', 'Hindi', 'English'],
    tags: ['literature', 'food', 'culture', 'music'],
    hourlyRate: 950,
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Tram Ride & Adda', emoji: '🚃' },
      { name: 'Bookstall Walk', emoji: '📖' },
      { name: 'Mishti Doi Trail', emoji: '🍮' },
    ],
  },
  {
    email: 'zara.hussain@demo.hana.app',
    name: 'Zara Hussain',
    displayName: 'Zara',
    age: 23,
    city: 'Lucknow',
    district: 'Hazratganj',
    bio: 'Nawabi Lucknow is my home — tehzeeb, kebabs, chikankari, and the most gracious hospitality you\'ll ever experience. Let me introduce you to the City of Nawabs.',
    languages: ['Urdu', 'Hindi', 'English'],
    tags: ['kebabs', 'chikankari', 'culture', 'nawabi'],
    hourlyRate: 900,
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Kebab Trail', emoji: '🍢' },
      { name: 'Chikankari Workshop', emoji: '🧵' },
      { name: 'Nawabi Heritage Walk', emoji: '🏰' },
    ],
  },
  {
    email: 'aditi.joshi@demo.hana.app',
    name: 'Aditi Joshi',
    displayName: 'Aditi',
    age: 26,
    city: 'Pune',
    district: 'Shivajinagar',
    bio: 'History buff and trekking enthusiast. Pune\'s forts, Peshwa history, and the Sahyadri ranges are my backyard. Let\'s go on an adventure that combines history and nature!',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['trekking', 'forts', 'history', 'nature'],
    hourlyRate: 1000,
    photos: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Fort Trek', emoji: '🏔️' },
      { name: 'Peshwa History Walk', emoji: '⚔️' },
      { name: 'Sahyadri Sunrise', emoji: '🌄' },
    ],
  },
  {
    email: 'lakshmi.pillai@demo.hana.app',
    name: 'Lakshmi Pillai',
    displayName: 'Lakshmi',
    age: 30,
    city: 'Thiruvananthapuram',
    district: 'Kowdiar',
    bio: 'Ayurveda practitioner and nature lover. Kerala\'s healing traditions, pristine beaches, and lush forests are my world. Let me guide you to true wellness and peace.',
    languages: ['Malayalam', 'Tamil', 'English'],
    tags: ['Ayurveda', 'wellness', 'beaches', 'nature'],
    hourlyRate: 1100,
    photos: [
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Ayurveda Walk', emoji: '🌿' },
      { name: 'Beach Sunrise', emoji: '🌊' },
      { name: 'Forest Trail', emoji: '🌳' },
    ],
  },
  {
    email: 'rhea.kapoor@demo.hana.app',
    name: 'Rhea Kapoor',
    displayName: 'Rhea',
    age: 24,
    city: 'Mumbai',
    district: 'Juhu',
    bio: 'Fashion stylist and social butterfly. Mumbai\'s fashion weeks, rooftop parties, and the best chaat at Juhu Beach — I know how to make any evening unforgettable.',
    languages: ['Hindi', 'English'],
    tags: ['fashion', 'nightlife', 'food', 'styling'],
    hourlyRate: 1500,
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Style Walk', emoji: '👗' },
      { name: 'Juhu Beach Chaat', emoji: '🍡' },
      { name: 'Rooftop Evening', emoji: '🌆' },
    ],
  },
  {
    email: 'sanya.malhotra@demo.hana.app',
    name: 'Sanya Malhotra',
    displayName: 'Sanya',
    age: 27,
    city: 'Delhi',
    district: 'Lajpat Nagar',
    bio: 'Foodie, shopper, and Delhi dil wali. From Chandni Chowk\'s parathas to Lajpat Nagar\'s bargains — I\'ll take you on a sensory overload that you\'ll absolutely love.',
    languages: ['Hindi', 'Punjabi', 'English'],
    tags: ['food', 'shopping', 'street food', 'markets'],
    hourlyRate: 1100,
    photos: [
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Chandni Chowk Food Walk', emoji: '🥘' },
      { name: 'Market Shopping', emoji: '🛍️' },
      { name: 'Old Delhi Walk', emoji: '🕌' },
    ],
  },
  {
    email: 'preethi.subramaniam@demo.hana.app',
    name: 'Preethi Subramaniam',
    displayName: 'Preethi',
    age: 25,
    city: 'Coimbatore',
    district: 'RS Puram',
    bio: 'Nature photographer and hill station lover. The Nilgiris, Ooty, and Kodaikanal are my canvas. Let me take you to misty mountains and tea estates that feel like a dream.',
    languages: ['Tamil', 'Kannada', 'English'],
    tags: ['photography', 'hills', 'nature', 'tea estates'],
    hourlyRate: 950,
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Tea Estate Walk', emoji: '🍃' },
      { name: 'Nilgiri Sunrise', emoji: '🌄' },
      { name: 'Photo Walk', emoji: '📸' },
    ],
  },
  {
    email: 'mansi.agarwal@demo.hana.app',
    name: 'Mansi Agarwal',
    displayName: 'Mansi',
    age: 29,
    city: 'Varanasi',
    district: 'Assi Ghat',
    bio: 'Spiritual seeker and Ganga devotee. Varanasi\'s ghats at dawn, the Ganga Aarti, silk weaving lanes, and the philosophy of this eternal city — I\'ll share it all with you.',
    languages: ['Hindi', 'Bhojpuri', 'English'],
    tags: ['spirituality', 'ghats', 'silk', 'philosophy'],
    hourlyRate: 800,
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Ganga Aarti', emoji: '🪔' },
      { name: 'Ghat Walk at Dawn', emoji: '🌅' },
      { name: 'Silk Weaving Lane', emoji: '🧶' },
    ],
  },
  // ===== NAGPUR =====
  {
    email: 'sakshi.thakre@demo.hana.app',
    name: 'Sakshi Thakre',
    displayName: 'Sakshi',
    age: 24,
    city: 'Nagpur',
    district: 'Sitabuldi',
    bio: 'Orange city girl with a love for street food and history. From Sitabuldi Fort to Itwari\'s bustling bazaars — I know every lane of Nagpur and I\'ll make your visit unforgettable.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['street food', 'history', 'bazaars', 'culture'],
    hourlyRate: 850,
    photos: [
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Itwari Bazaar Walk', emoji: '🛍️' },
      { name: 'Orange Orchard Visit', emoji: '🍊' },
      { name: 'Sitabuldi Fort Tour', emoji: '🏰' },
    ],
  },
  {
    email: 'prachi.deshmukh@demo.hana.app',
    name: 'Prachi Deshmukh',
    displayName: 'Prachi',
    age: 26,
    city: 'Nagpur',
    district: 'Dharampeth',
    bio: 'Yoga instructor and wellness enthusiast from Dharampeth. Nagpur\'s serene lakes, morning parks, and the famous Ambazari Garden are my happy places. Let\'s start your day right!',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['yoga', 'wellness', 'parks', 'nature'],
    hourlyRate: 900,
    photos: [
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Ambazari Garden Walk', emoji: '🌿' },
      { name: 'Morning Yoga Session', emoji: '🧘' },
      { name: 'Lake Sunrise', emoji: '🌅' },
    ],
  },
  {
    email: 'neha.bhagat@demo.hana.app',
    name: 'Neha Bhagat',
    displayName: 'Neha',
    age: 23,
    city: 'Nagpur',
    district: 'Sadar',
    bio: 'Foodie and chai lover from Sadar. Nagpur\'s saoji cuisine, tarri poha, and the iconic VCA stadium area — I\'ll take you on a flavour journey through the heart of Vidarbha.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['food', 'chai', 'saoji', 'local cuisine'],
    hourlyRate: 800,
    photos: [
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Saoji Food Trail', emoji: '🍛' },
      { name: 'Tarri Poha Morning', emoji: '🍽️' },
      { name: 'Chai & Conversation', emoji: '☕' },
    ],
  },
  {
    email: 'rutuja.wankhede@demo.hana.app',
    name: 'Rutuja Wankhede',
    displayName: 'Rutuja',
    age: 27,
    city: 'Nagpur',
    district: 'Ramdaspeth',
    bio: 'Art teacher and craft enthusiast. Nagpur\'s Warli art tradition, handloom weaving villages, and the creative community of Ramdaspeth — I\'ll show you the artistic soul of the city.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['art', 'craft', 'Warli', 'handloom'],
    hourlyRate: 950,
    photos: [
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Warli Art Workshop', emoji: '🎨' },
      { name: 'Handloom Village', emoji: '🧵' },
      { name: 'Creative Café Hop', emoji: '☕' },
    ],
  },
  {
    email: 'ankita.meshram@demo.hana.app',
    name: 'Ankita Meshram',
    displayName: 'Ankita',
    age: 25,
    city: 'Nagpur',
    district: 'Civil Lines',
    bio: 'History buff and heritage lover. Nagpur\'s colonial Civil Lines, the Residency ruins, and the zero mile marker — I\'ll walk you through the city\'s fascinating past layer by layer.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['heritage', 'colonial history', 'architecture', 'walks'],
    hourlyRate: 875,
    photos: [
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Civil Lines Heritage Walk', emoji: '🏛️' },
      { name: 'Zero Mile Marker', emoji: '📍' },
      { name: 'Residency Ruins Tour', emoji: '🏚️' },
    ],
  },
  {
    email: 'shruti.gawande@demo.hana.app',
    name: 'Shruti Gawande',
    displayName: 'Shruti',
    age: 28,
    city: 'Nagpur',
    district: 'Hingna',
    bio: 'Wildlife enthusiast and nature photographer. Nagpur is the gateway to Tadoba and Pench — I\'ll plan the perfect jungle safari experience and show you why this city is India\'s tiger capital.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['wildlife', 'safari', 'photography', 'nature'],
    hourlyRate: 1100,
    photos: [
      'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Safari Planning', emoji: '🐯' },
      { name: 'Nature Photography', emoji: '📸' },
      { name: 'Forest Walk', emoji: '🌳' },
    ],
  },
  {
    email: 'pooja.nagpure@demo.hana.app',
    name: 'Pooja Nagpure',
    displayName: 'Pooja N',
    age: 22,
    city: 'Nagpur',
    district: 'Manewada',
    bio: 'Music lover and classical Kathak dancer. Nagpur\'s vibrant cultural scene — from Ganesh festival celebrations to classical music sabhas — is where I feel most alive. Let me share it with you!',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['Kathak', 'music', 'festivals', 'culture'],
    hourlyRate: 900,
    photos: [
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Kathak Performance', emoji: '💃' },
      { name: 'Music Sabha Evening', emoji: '🎶' },
      { name: 'Festival Walk', emoji: '🪔' },
    ],
  },
  {
    email: 'varsha.kadu@demo.hana.app',
    name: 'Varsha Kadu',
    displayName: 'Varsha',
    age: 30,
    city: 'Nagpur',
    district: 'Laxmi Nagar',
    bio: 'Entrepreneur and coffee connoisseur. Nagpur\'s growing café culture, co-working spaces, and the startup ecosystem of Laxmi Nagar — I\'m your guide to the city\'s modern, ambitious side.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['coffee', 'startups', 'cafés', 'networking'],
    hourlyRate: 1050,
    photos: [
      'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Café Culture Tour', emoji: '☕' },
      { name: 'Startup Hub Visit', emoji: '💡' },
      { name: 'Evening Networking', emoji: '🤝' },
    ],
  },
  {
    email: 'kajal.bawane@demo.hana.app',
    name: 'Kajal Bawane',
    displayName: 'Kajal',
    age: 24,
    city: 'Nagpur',
    district: 'Gandhibagh',
    bio: 'Textile designer and shopping guide. Gandhibagh\'s famous cloth markets, Nagpur\'s unique cotton industry, and the best saree shops in the city — I\'ll help you find the most beautiful fabrics.',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['textiles', 'shopping', 'sarees', 'cotton'],
    hourlyRate: 825,
    photos: [
      'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'Cloth Market Walk', emoji: '🧶' },
      { name: 'Saree Shopping', emoji: '👘' },
      { name: 'Cotton Mill Tour', emoji: '🏭' },
    ],
  },
  {
    email: 'dipti.raut@demo.hana.app',
    name: 'Dipti Raut',
    displayName: 'Dipti',
    age: 26,
    city: 'Nagpur',
    district: 'Pratap Nagar',
    bio: 'Sports enthusiast and cricket lover. Nagpur\'s VCA Stadium, the city\'s love for cricket, and the electric atmosphere of a match day — I\'ll give you the full Nagpur sports experience!',
    languages: ['Marathi', 'Hindi', 'English'],
    tags: ['cricket', 'sports', 'stadium', 'fitness'],
    hourlyRate: 875,
    photos: [
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=600&h=800&fit=crop&crop=face',
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=600&h=800&fit=crop&crop=face',
    ],
    experiences: [
      { name: 'VCA Stadium Tour', emoji: '🏏' },
      { name: 'Morning Sports Walk', emoji: '🏃' },
      { name: 'Local Game Watch', emoji: '🎯' },
    ],
  },
]

async function main() {
  console.log('Clearing old data...')
  await prisma.experience.deleteMany()
  await prisma.availability.deleteMany()
  await prisma.companion.deleteMany()
  await prisma.user.deleteMany({ where: { email: { endsWith: '@demo.hana.app' } } })

  console.log('Seeding 20 Indian companions...')

  for (const data of COMPANIONS) {
    const user = await prisma.user.upsert({
      where: { email: data.email },
      update: {},
      create: {
        email: data.email,
        name: data.name,
        role: 'COMPANION',
        city: data.city,
      },
    })

    const companion = await prisma.companion.upsert({
      where: { userId: user.id },
      update: {},
      create: {
        userId: user.id,
        displayName: data.displayName,
        age: data.age,
        city: data.city,
        district: data.district,
        bio: data.bio,
        languages: data.languages,
        photos: data.photos,
        tags: data.tags,
        hourlyRate: data.hourlyRate,
        isActive: true,
        isFeatured: COMPANIONS.indexOf(data) < 6,
        verificationStatus: 'VERIFIED',
        averageRating: 4.2 + Math.random() * 0.75,
        totalReviews: Math.floor(Math.random() * 30) + 8,
        totalBookings: Math.floor(Math.random() * 50) + 15,
      },
    })

    for (const exp of data.experiences) {
      await prisma.experience.create({
        data: { companionId: companion.id, name: exp.name, emoji: exp.emoji },
      })
    }

    for (let day = 1; day <= 6; day++) {
      await prisma.availability.upsert({
        where: { companionId_dayOfWeek: { companionId: companion.id, dayOfWeek: day } },
        update: {},
        create: {
          companionId: companion.id,
          dayOfWeek: day,
          startTime: '10:00',
          endTime: '21:00',
          isAvailable: true,
        },
      })
    }

    console.log(`  ✓ ${data.name} — ${data.city}`)
  }

  console.log('\n🌸 Seeding complete! 20 companions added.')
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
